class MatchConstants:

    HTTP_ERROR = "HttpError"
    DNSLOOKUP_ERROR = "DNSLookupError"
    TIMEOUT_ERROR = "TimeoutError"
    CONNECTION_LOST = "ConnectionLost"


    TYPE_OP_SAVE_OR_FIND_ERROR_BY_CHAMPIONSHIP_JOB = "OP_SAVE_OR_FIND_COLLECTION"
    TYPE_OP_FIND_ERRORS = "OP_FIND_ERRORS"
    TYPE_OP_DROP_OR_FIND_ERROR_BY_NAME_COLLECTION = "OP_DROP_OR_FIND_NAME_COLLECTION"

    HTTP_CLIENT_SUCCESS_200 = "Client OK: Request Executed"
    HTTP_CLIENT_ERROR_404 = "Client Error: Resource not found"
    HTTP_CLIENT_ERROR_401 = "Client Error: Unauthorized access"
    HTTP_CLIENT_ERROR_500 = "Server Error: Internal Error"

    HTTP_SUCCESS_STATUS = 200
    HTTP_ERROR_INTERNAL_CODE = 500
    HTTP_ERROR_BAD_GATEWAY_CODE = 502
    HTTP_ERROR_UNAVAILABLE_CODE = 503
    HTTP_ERROR_TIMEOUT_CODE = 504

    # SpiderName - Instance
    MATCH_SOCCER_SPIDER = "matchsoccer"

    # ACRONYM - COLLECTION
    DOMAIN_SCRAPY_CHAMPIONSHIP = "_chmp"
    DOMAIN_SCRAPY_ERROR = "_error_"


